language: python
python:
 - 2.7

env:
  - TOX_ENV=py25
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=flakes

install:
    pip install tox

script: tox -e $TOX_ENV

notifications:
    email:
        - lukaszbalcerzak@gmail.com
        - marcinkuz@gmail.com
    irc: "irc.freenode.org#vcs"
